# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 23:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('rollno', models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter a valid Roll number.', regex='^(\\d{2}|\\d{8})([a-z]{2}|[A-Z]{2})\\d{2,3}([a-z]{1}|[A-Z]{1})?$')])),
                ('mobileno', models.CharField(default='+91', max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(default='', max_length=254)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
