# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 18:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptrecdata',
            name='ans1',
        ),
        migrations.RemoveField(
            model_name='cryptrecdata',
            name='ans2',
        ),
        migrations.AddField(
            model_name='cryptrecdata',
            name='day_to_slot',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='cryptrecdata',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cryptrecdata',
            name='reviewer_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cryptrecdata',
            name='reviewer_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cryptrecdata',
            name='reviewer_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cryptrecdata',
            name='score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
