# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crypt', '0003_auto_20170717_2337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CryptForm',
            new_name='Crypt',
        ),
        migrations.DeleteModel(
            name='CryptRecData',
        ),
    ]
