# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypt', '0004_auto_20170718_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypt',
            name='q1',
            field=models.CharField(max_length=50),
        ),
    ]
